services:
  postgres:
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: rss_aggregator
    volumes:
      - ./data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - 8001:8001
      - 9229:9229 # for debugging
    environment:
      PORT: 8001
      DATABASE_URL: postgres://postgres@postgres/rss_aggregator
    volumes:
      - .:/usr/src/app
      - /usr/src/app/.pnpm-store
      - /usr/src/app/node_modules
    command: pnpm start:docker
    depends_on:
      - postgres
